name: Rust

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: cargo login
      env: TOKEN:${{ secrets.cratelogin }}
      run: cargo login TOKEN
    - name: publish
      run: cargo publish --verbose
